/*  =========================================================================
    zee - generated layer of public API

      LGPL 3+

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZEE_LIBRARY_H_INCLUDED
#define ZEE_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>

//  ZEE version macros for compile-time API detection
#define ZEE_VERSION_MAJOR 0
#define ZEE_VERSION_MINOR 0
#define ZEE_VERSION_PATCH 0

#define ZEE_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define ZEE_VERSION \
    ZEE_MAKE_VERSION(ZEE_VERSION_MAJOR, ZEE_VERSION_MINOR, ZEE_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined ZEE_STATIC
#       define ZEE_EXPORT
#   elif defined ZEE_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define ZEE_EXPORT __declspec(dllexport)
#       else
#           define ZEE_EXPORT
#       endif
#   elif defined ZEE_EXPORTS
#       define ZEE_EXPORT __declspec(dllexport)
#   else
#       define ZEE_EXPORT __declspec(dllimport)
#   endif
#   define ZEE_PRIVATE
#elif defined (__CYGWIN__)
#   define ZEE_EXPORT
#   define ZEE_PRIVATE
#else
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define ZEE_PRIVATE __attribute__ ((visibility ("hidden")))
#       define ZEE_EXPORT __attribute__ ((visibility ("default")))
#   else
#       define ZEE_PRIVATE
#       define ZEE_EXPORT
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  ZEE_BUILD_DRAFT_API
#define ZEE_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef ZEE_BUILD_DRAFT_API
typedef struct _zee_proto_t zee_proto_t;
#define ZEE_PROTO_T_DEFINED
typedef struct _zee_server_t zee_server_t;
#define ZEE_SERVER_T_DEFINED
typedef struct _zee_client_t zee_client_t;
#define ZEE_CLIENT_T_DEFINED
#endif // ZEE_BUILD_DRAFT_API


//  Public classes, each with its own header file
#ifdef ZEE_BUILD_DRAFT_API
#include "zee_proto.h"
#include "zee_server.h"
#include "zee_client.h"
#endif // ZEE_BUILD_DRAFT_API

#ifdef ZEE_BUILD_DRAFT_API

#ifdef __cplusplus
extern "C" {
#endif

//  Self test for private classes
ZEE_EXPORT void
    zee_private_selftest (bool verbose, const char *subtest);

#ifdef __cplusplus
}
#endif
#endif // ZEE_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
