/*  =========================================================================
    zee_classes - private header file

      LGPL 3+
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef ZEE_CLASSES_H_INCLUDED
#define ZEE_CLASSES_H_INCLUDED

//  Platform definitions, must come first
#include "platform.h"

//  External API
#include "../include/zee.h"

//  Opaque class structures to allow forward references

//  Extra headers

//  Internal API


//  *** To avoid double-definitions, only define if building without draft ***
#ifndef ZEE_BUILD_DRAFT_API

//  Self test for private classes
ZEE_PRIVATE void
    zee_private_selftest (bool verbose, const char *subtest);

#endif // ZEE_BUILD_DRAFT_API

#endif
